# -*- coding: utf-8 -*-
print "Hellow,world!"
print "Hellow again"
print "I like trping this."
print "This is fun."
print "Yay,printing."
print "I'd much rather you 'not'"
print "I 'said' you do not touch this."
print "我在学习Python语言。"
print "I am learning Python language."
